services:
  guia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guia-jsp
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - coolify

networks:
  coolify:
    external: true