import os
import re

"""
Rebuild css/styles.css from modules but with fixes for broken boundaries.
Each module is made self-contained by adding missing braces.
"""

MODULES_DIR = r'C:\Users\Miguel\Documents\Aplicaciones\_projects\guia-jsp\web\css\modules'
OUTPUT = r'C:\Users\Miguel\Documents\Aplicaciones\_projects\guia-jsp\web\css\styles.css'

MODULE_ORDER = [
    'base.css',
    'layout.css',
    'hero.css',
    'sections.css',
    'sidebar-nav.css',
    'components.css',
    'code-blocks.css',
    'modules-tech.css',
    'quiz-search.css',
    'enhancements.css',
    'ux-enhancements.css',
]

# Known boundary fixes: (filename, leading_braces_to_add, trailing_braces_to_add)
# These compensate for rules that are split across file boundaries
BOUNDARY_FIXES = {
    # 'hero.css': (0, 1),          # Fixed in source - no longer needed
    # 'sections.css': (0, 1),      # Fixed in source - no longer needed
    # 'quiz-search.css': (0, 1),   # Fixed in source - no longer needed
}

def fix_braces(content, open_braces, close_braces):
    """Add missing braces at start or end."""
    if open_braces > 0:
        content = '{' * open_braces + '\n' + content
    if close_braces > 0:
        content = content.rstrip() + '\n' + '}' * close_braces + '\n'
    return content

parts = []
parts.append('/* ============================================')
parts.append('   styles.css - Production CSS (auto-generated)')
parts.append('   Generated by rebuild_css.py')
parts.append('   ============================================ */\n')

for fname in MODULE_ORDER:
    path = os.path.join(MODULES_DIR, fname)
    if not os.path.exists(path):
        print(f'WARNING: {fname} not found')
        continue
    
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    add_open, add_close = BOUNDARY_FIXES.get(fname, (0, 0))
    fixed = fix_braces(content, add_open, add_close)
    
    parts.append(f'\n/* --- module: {fname} --- */\n')
    parts.append(fixed)
    
    ob = fixed.count('{')
    cb = fixed.count('}')
    bal = ob - cb
    print(f'  {fname}: {len(content)} chars, {ob} open, {cb} close, bal={bal}')

result = '\n'.join(parts)

with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write(result)

total_ob = result.count('{')
total_cb = result.count('}')
print(f'\nTotal: {total_ob} open, {total_cb} close, bal={total_ob - total_cb}')
print(f'Output: {OUTPUT} ({len(result)} chars, {result.count(chr(10))+1} lines)')
